--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: notification_reservations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification_reservations (
    id bigint NOT NULL,
    email character varying(255),
    reserved boolean NOT NULL
);


ALTER TABLE public.notification_reservations OWNER TO postgres;

--
-- Name: notification_reservations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notification_reservations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_reservations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    amount integer NOT NULL,
    category character varying(255) NOT NULL,
    content character varying(255),
    date character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    email character varying(255) DEFAULT 'default@example.com'::character varying NOT NULL
);


ALTER TABLE public.transactions OWNER TO postgres;

--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.transactions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.transactions_id_seq OWNER TO postgres;

--
-- Name: transactions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.transactions_id_seq OWNED BY public.transactions.id;


--
-- Name: transactions id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions ALTER COLUMN id SET DEFAULT nextval('public.transactions_id_seq'::regclass);


--
-- Data for Name: notification_reservations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notification_reservations (id, email, reserved) FROM stdin;
1	test@gmail.com	t
2	test@gmail.com	t
3	test@gmail.com	t
\.


--
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transactions (id, amount, category, content, date, type, email) FROM stdin;
7	2000	食費	ハンバーガー	2025-07-01	expense	test@gmail.com
8	1200000	給与	SE	2025-07-01	income	test@gmail.com
11	6000	交通費	静岡	2025-07-14	expense	test@gmail.com
18	10000	交際費	接待	2025-07-29	expense	test@gmail.com
21	500010	副収入	手付	2025-07-30	income	test@gmail.com
10	4000	娯楽	テニス	2025-07-08	expense	test@gmail.com
24	4500	食費	ハンバーガー	2025-08-01	expense	test@gmail.com
25	200040	給与	本職	2025-08-02	income	test@gmail.com
27	56000	住居費	家賃	2025-08-04	expense	test@gmail.com
28	3000	お小遣い	手当	2025-08-02	income	test@gmail.com
\.


--
-- Name: notification_reservations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notification_reservations_id_seq', 3, true);


--
-- Name: transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transactions_id_seq', 28, true);


--
-- Name: notification_reservations notification_reservations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification_reservations
    ADD CONSTRAINT notification_reservations_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

